[package]
name = "providence-io"
version = "0.1.0"
edition = "2021"
description = "ğŸ‘ data and I/O"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
bincode = "1.3.3"
async-io = "2.3.2"
async-task = "4.5.0"
async-executor = "1.11.0"
futures-lite = "2.0.1"
uwuhi-async = "0.4.1"
if-addrs = "0.12.0"
tracing = "0.1.40"
pawawwewism = "0.1.0"

# importantly, this library does not pull in `Zaru` and the wgpu stack
# (that's done by the containing package that also contains the binaries)
