[package]
name = "providence-io"
version = "0.1.0"
edition = "2021"
description = "ğŸ‘ data and I/O"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
bincode = "1.3.3"
async-std = "1.12.0"
futures-lite = "1.13.0"
uwuhi-async = "0.3.0"
if-addrs = "0.10.1"
log = "0.4.17"

# importantly, this library does not pull in `Zaru` and the wgpu stack
# (that's done by the containing package that also contains the binaries)

[dev-dependencies]
env_logger = "0.10.0"
