[package]
name = "providence-io"
version = "0.1.0"
edition = "2021"
description = "ğŸ‘ data and I/O"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
bincode = "1.3.3"
async-std = "1.12.0"
futures = "0.3.25"
uwuhi-async = "0.3.0"
if-addrs = "0.8.0"
log = "0.4.17"

[dev-dependencies]
env_logger = "0.10.0"
