[package]
name = "providence"
version = "0.1.0"
edition = "2021"
description = "ğŸ‘"

[dependencies]
zaru = { git = "https://github.com/SludgePhD/Zaru.git", rev = "dc0c449301e2ea3eb21c9df20cf901e3cc2f4176" }
uwuhi-async = "0.3.0"
pawawwewism = "0.1.0"
log = "0.4.17"
serde = { version = "1.0.145", features = ["derive"] }
bincode = "1.3.3"
if-addrs = "0.7.0"
async-std = "1.12.0"
futures = "0.3.24"
nalgebra = "0.31.4"

[dev-dependencies]
env_logger = "0.10.0"
macroquad = "0.3.24"

[profile.dev]
opt-level = 2
