[package]
name = "providence"
version = "0.1.0"
edition = "2021"
description = "ğŸ‘"

[dependencies]
zaru = { git = "https://github.com/SludgePhD/Zaru.git", rev = "42a232185074c1e18f07187d25a5ab51bf52fe06" }
uwuhi-async = "0.3.0"
pawawwewism = "0.1.0"
log = "0.4.17"
serde = { version = "1.0.145", features = ["derive"] }
bincode = "1.3.3"
spade = "2.0.0"
rustc-hash = "1.1.0"
indexmap = "1.9.1"
if-addrs = "0.7.0"
async-std = "1.12.0"
futures = "0.3.24"
glam = "0.22.0"

[dev-dependencies]
env_logger = "0.10.0"
macroquad = "0.3.24"

[profile.dev]
opt-level = 2
