[package]
name = "providence"
version = "0.1.0"
edition = "2021"
description = "ğŸ‘"

[dependencies]
zaru = { git = "https://github.com/SludgePhD/Zaru.git", rev = "2ee531a5c51f2ad7a84f22e68dff812b2e9c4de3" }
#uwuhi = "0.2.0"
uwuhi-async = { path = "../uwuhi/uwuhi-async" }
pawawwewism = "0.1.0"
log = "0.4.17"
serde = { version = "1.0.145", features = ["derive"] }
bincode = "1.3.3"
spade = "2.0.0"
rustc-hash = "1.1.0"
indexmap = "1.9.1"
if-addrs = "0.7.0"
async-std = "1.12.0"
futures = "0.3.24"

[dev-dependencies]
env_logger = "0.9.1"

[workspace]
members = [".", "viewer"]

[profile.dev]
opt-level = 2
