[package]
name = "providence-data"
version = "0.1.0"
edition = "2021"
description = "ğŸ‘ data"

[dependencies]
serde = { version = "1.0.145", features = ["derive"] }
bincode = "1.3.3"
futures = "0.3.25"
